import { Popover } from '@headlessui/react';
import * as PopoverPrimitive from '@radix-ui/react-popover';
import Head from 'next/head';

import { Column } from '../lib/primitives';
import { Box } from '../lib/primitives/Box/Box';
import { Grid } from '../lib/primitives/Grid';
import { atoms } from '../styles/atoms.css';
import { openPopoverButton, popoverButton, popoverContent } from '../styles/home.css';

import type { NextPage } from 'next';
const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div
				className={atoms({
					margin: 'space9',
				})}
			>
				<PopoverPrimitive.Root>
					<PopoverPrimitive.Trigger className={popoverButton}>
						Hi! I am button
					</PopoverPrimitive.Trigger>
					<PopoverPrimitive.Content className={popoverContent}>
						<PopoverPrimitive.Arrow />
						<Column width={'content'}>
							<Box>Item 1</Box>
							<Box>Item 2</Box>
							<Box>Item 3</Box>
						</Column>
					</PopoverPrimitive.Content>
				</PopoverPrimitive.Root>
				<Popover>
					{({ open }) => (
						<>
							<Popover.Button className={open ? openPopoverButton : popoverButton}>
								Hi! I am button
							</Popover.Button>
							<Popover.Panel className={popoverContent}>
								<Grid minItemWidth={200}>
									<Box>
										<input type="checkbox" id="checkbox" />
										<label htmlFor="checkbox">Label 1</label>
									</Box>
									<Box>Item 2</Box>
									<Box>Item 3</Box>
								</Grid>
							</Popover.Panel>
						</>
					)}
				</Popover>
			</div>
		</>
	);
};

export default Home;
